---
title: "ESM 244 Lab 1 Rathbone"
author: "Vanessa Rathbone"
date: "1/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Attach packages
library(tidyverse)
library(here)
library(sf)
library(tmap)

```

### Read in SF trees data 
```{r}

#read in data
sf_trees <- read_csv(here("data", "sf_trees", "sf_trees.csv"))

```

### Basic wrangling reminders 

Refresh some skills for data wrangling and summary statistics using functions in the 'dplyr' package.

Find the top 5 highest observations of trees by legal_status, do some wrangling, make a graph.
```{r}

#wrangle and clean up data
#count is 1) recognising groups, 2) replaces N function, 3) and summarizes function

top_5_status <- sf_trees %>% 
  count(legal_status) %>% #could add another group levels like count(legal_status, species)
  drop_na(legal_status) %>% #drop any NA values, in sf_trees it's group 10
  rename(tree_count = n) %>% 
  relocate(tree_count) %>%   #move columns around in df, similar to select function but simpler for multiple columns
  slice_max(tree_count, n = 5) #like head function but interactive if more values are added in the future, finds top 5 in this case


```

